config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards do
    resources :lists, except: :show do
      resources :items
    end
    resources :board_users, only: [ :new, :create ]
  end

  namespace :api do
    resources :boards do
      resources :lists, only: :index, controller: "lists"
      resources :list_positions, only: [ :index, :update ], controller: "list_positions"
    end
    put "item_positions", to: "item_positions#update"

    resources :items, only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy

  validates :name, presence: true

  has_many :board_users, dependent: :destroy
  has_many :members, through: :board_users, source: :user

  after_create :assign_user_as_member

  def assign_user_as_member
    members << user
  end
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/item_positions_controller.rb
module Api
  class ItemPositionsController < ApplicationController
    protect_from_forgery with: :null_session

    def update
      @items = Items::Commands::UpdatePosition.new.call(items_data: items_params[:items])

      render json: ItemSerializer.new(@items).serializable_hash.to_json
    end

    private

    def items_params
      params.permit(items: [ :id, :position, :list_id ])
    end
  end
end

app/controllers/api/items_controller.rb
module Api
  class ItemsController < ApplicationController
    protect_from_forgery with: :null_session

    def show
      @item = Items::Queries::Get.new.call(item_id: params[:id])

      render json: ItemSerializer.new(@item).serializable_hash.to_json
    end
  end
end

app/controllers/api/list_positions_controller.rb
module Api
  class ListPositionsController < ApplicationController
    protect_from_forgery with: :null_session, only: :update

    def update
      @lists = Lists::Commands::UpdatePosition.new.call(id: params[:id], board_id: params[:board_id], position: params[:position])

      render json: ListSerializer.new(@lists).serializable_hash.to_json
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApplicationController
    def index
      @lists = Lists::Queries::GetByBoard.new.call(board_id: params[:board_id])

      render json: ListSerializer.new(@lists).serializable_hash.to_json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pundit::Authorization
  include Dry::Monads[:result]
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @board_user, @users = BoardUsers::Queries::NewBoardUser.new.call(board:)
  end

  def edit
    authorize board
  end

  def create
    BoardUsers::Commands::UpdateMembers.new.call(id: params[:board_id], params: board_user_params)

    redirect_to board_path(board)
  end

  private

  def board_user_params
    params.require(:board_user).permit(user_ids: [])
  end

  def board
    @board ||= Boards::Queries::Get.new.call(id: params[:board_id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def show
    authorize board
  end

  def create
    result = Boards::Commands::Create.new.call(params: board_params, user: current_user)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :new
    end
  end

  def update
    authorize board
    result = Boards::Commands::Update.new.call(id: params[:id], params: board_params)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :edit
    end
  end

  def destroy
    authorize board

    result = Boards::Commands::Delete.new.call(id: params[:id])

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      redirect_to root_path
    end
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Boards::Queries::Get.new.call(id: params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Boards::Queries::GetByUser.new.call(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = list.items.new
  end

  def create
    result = Items::Commands::Create.new.call(params: item_params, list:)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :new
    end
  end

  def edit
    board
    list
    @item = Items::Queries::GetByList.new.call(item_id: params[:id], list:)
  end

  def update
    result = Items::Commands::Update.new.call(id: params[:id], params: item_params)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :edit
    end
  end

  def destroy
    result = Items::Commands::Delete.new.call(id: params[:id])

    case result
    in Success(:success)
      respond_to do |format|
        format.json do
          render json: {}, status: 204
        end
      end
    in Failure(:invalid)
      respond_to do |format|
        format.json do
          render json: {}, status: 204
        end
      end
    end
  end

  private

  def board
    @board ||= Boards::Queries::Get.new.call(id: params[:board_id])
  end

  def list
    @list ||= Repositories::ListRepo.new.get(id: params[:list_id], board:)
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, only: :destroy

  def new
    @list = board.lists.new
  end

  def create
    result = Lists::Commands::Create.new.call(params: list_params, board:)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :new
    end
  end

  def update
    result = Lists::Commands::Update.new.call(id: params[:id], params: list_params, board:)

    case result
    in Success(:success)
      redirect_to root_path
    in Failure(:invalid)
      render :edit
    end
  end

  def destroy
    result = Lists::Commands::Delete.new.call(id: params[:id])

    case result
    in Success(:success)
      respond_to do |format|
        format.json do
          render json: {}, status: 204
        end
      end
    in Failure(:invalid)
      respond_to do |format|
        format.json do
          render json: {}, status: 204
        end
      end
    end
  end

  def edit
    @list = Lists::Queries::Get.new.call(id: params[:id], board:)
  end

  private

  def board
    @board ||= Boards::Queries::Get.new.call(id: params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/board_users/_form.html.erb
<div class="bg-white mt-12 px-8 py-8 rounded-md">
  <%= form_with model: [board, board_user], url: board_board_users_path(board), local: true do |f| %>
    <div class="space-y-12">
      <div class="border-b border-gray-900/10 pb-12">
        <div>
          <div class="mb-5">
            <h2 class="text-base/7 font-semibold text-gray-900">Board Member List</h2>
            <p class="mt-1 text-sm/6 text-gray-600">This form adds/remove board members.</p>
          </div>

          <fieldset>
            <legend class="text-lg font-medium text-gray-900">Members</legend>

            <div class="mt-4 divide-y divide-gray-200 border-t border-b border-gray-200">
              <% users.each do |user| %>
                <div class="relative flex items-start py-4">
                  <div class="min-w-0 flex-1 text-sm">
                    <%= f.label :user_ids, class: "select-none font-medium text-gray-700" do %>
                      <%= user.email %>
                    <% end %>
                  </div>

                  <div class="ml-3 flex h5 items-center">
                    <%= f.check_box :user_ids, {multiple: true, checked: board.members.include?(user), disabled: board.user==user, class:"h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"}, user.id %>
                  </div>
                </div>
              <% end %>
            </div>
          </fieldset>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "text-sm/6 font-semibold text-gray-900" %>
      <%= f.submit "Assign Members", class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60" %>
    </div>
  <% end %>
</div>

app/views/board_users/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <%= render "form", board: @board, board_user: @board_user, users: @users %>
  </div>
</div>

app/views/boards/_form.html.erb
<div class="bg-white mt-12 px-8 py-8 rounded-md">
  <%= form_with model: board, local: true do |f| %>
    <div class="space-y-12">
      <div class="border-b border-gray-900/10 pb-12">
        <% if board.new_record? %>
          <h2 class="text-base/7 font-semibold text-gray-900">New Board</h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form create a new board.</p>
        <% else %>
          <h2 class="text-base/7 font-semibold text-gray-900">Edit Board: <%= board.name %></h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form edits a board.</p>
        <% end %>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="col-span-full">
            <%= f.label :name, class: "block text-sm/6 font-medium text-gray-900" %>
            <div class="mt-2">
              <%= f.text_field :name, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "text-sm/6 font-semibold text-gray-900" %>
      <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60" %>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="mx-auto max-w-full px-24 sm:px-6 lg:px-8 py-12">
  <div class="mb-5">
    <%= link_to "+ Add New Member", new_board_board_user_path(@board), class: "inline-flex item-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
  </div>

  <div 
    class="mx-auto max-w-full" 
    id="board" 
    style="overflow-x: scroll;" 
    data-controller="board"
    data-api-url="<%= api_board_lists_path(@board) %>"
    data-list-position-api-url="<%= api_board_list_positions_path(@board) %>"
    data-item-position-api-url="<%= api_item_positions_path %>"
    data-board-lists-url="<%= board_lists_path(@board) %>"
    data-board-id="<%= @board.id %>"
  >
  </div>
</div>

<%= render "shared/modal" %>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <% @boards.each do |board| %>
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
          <div class="flex w-full items-center justify-between space-x-6 p-6">
            <div class="flex-1 truncate">
              <div class="flex item-center space-x-3">
                <h3 class="truncate text-sm font-medium text-gray-900"><%= link_to board.name, board_path(board), class: "link" %></h3>
              </div>
            </div>
          </div>
          <div>
            <div class="-mt-px flex divide-x divide-gray-200">
              <div class="flex w-0 flex-1">
                <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg broader boarder-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span>Edit</span>
                <% end %>
              </div>
              <div class="-ml-px flex w-0 flex-1">
                <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg broader boarder-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span class="text-red-500">Delete</span>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<p>Hello World!</p>

app/views/items/_form.html.erb
<div class="bg-white mt-12 px-8 py-8 rounded-md">
  <%= form_with model: [board, list, item], local: true do |f| %>
    <div class="space-y-12">
      <div class="border-b border-gray-900/10 pb-12">
        <% if item.new_record? %>
          <h2 class="text-base/7 font-semibold text-gray-900">New Item</h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form create a new item.</p>
        <% else %>
          <h2 class="text-base/7 font-semibold text-gray-900">Edit Item: <%= item.title %></h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form edits a item.</p>
        <% end %>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="col-span-full">
            <%= f.label :title, class: "block text-sm/6 font-medium text-gray-900" %>
            <div class="mt-2">
              <%= f.text_field :title, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" %>
            </div>
          </div>
        </div>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="col-span-full">
            <%= f.label :description, class: "block text-sm/6 font-medium text-gray-900" %>
            <div class="mt-2">
              <%= f.text_area :description, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "text-sm/6 font-semibold text-gray-900" %>
      <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60" %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <%= render "form", board: @board, list: @list, item: @item %>
  </div>
</div>

app/views/items/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <%= render "form", board: @board, list: @list, item: @item %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex shrink-0 items-center">
          <%= link_to  root_path do %>
            <%= image_tag "Trello_logo.png", class: "h-8 w-auto" %>
          <% end %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <% if user_signed_in? %>
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <%= link_to "Dashboard", root_path, class: "rounded-md px-3 py-2 text-sm font-medium #{controller_name == "dashboard" ? "text-white bg-gray-900" : "text-gray-300 hover:bg-gray-700 hover:text-white"}" %>
              <!-- <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a> -->
              <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete}, class: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <% if user_signed_in? %>
          <div class="flex-shrink-0">
            <% if controller_name == "boards" && action_name == "show" %>
              <%= link_to new_board_list_path(@board), class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-1 font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="-ml-1 mr-2 h-5 w-5">
                  <path d="M10.75 4.75a.75.75 0 0 0-1.5 0v4.5h-4.5a.75.75 0 0 0 0 1.5h4.5v4.5a.75.75 0 0 0 1.5 0v-4.5h4.5a.75.75 0 0 0 0-1.5h-4.5v-4.5Z"></path>
                </svg>
                New List
              <% end %>
            <% else %>
              <%= link_to new_board_path, class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-1 font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="-ml-1 mr-2 h-5 w-5">
                  <path d="M10.75 4.75a.75.75 0 0 0-1.5 0v4.5h-4.5a.75.75 0 0 0 0 1.5h4.5v4.5a.75.75 0 0 0 1.5 0v-4.5h4.5a.75.75 0 0 0 0-1.5h-4.5v-4.5Z"></path>
                </svg>
                New Board
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="ml-4 flex flex-shrink-0 items-center">
            <%= link_to "Register", new_user_registration_path, class: "link" %>
            <%= link_to "Log In", new_user_session_path, class: "ml-3 link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Trello Clone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/jkanban@1.3.1/dist/jkanban.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/jkanban@1.3.1/dist/jkanban.min.css" rel="stylesheet">
  </head>

  <body class="bg-gray-400">
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="bg-white mt-12 px-8 py-8 rounded-md">
  <%= form_with model: [board, list], local: true do |f| %>
    <div class="space-y-12">
      <div class="border-b border-gray-900/10 pb-12">
        <% if list.new_record? %>
          <h2 class="text-base/7 font-semibold text-gray-900">New List</h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form create a new list.</p>
        <% else %>
          <h2 class="text-base/7 font-semibold text-gray-900">Edit List: <%= list.title %></h2>
          <p class="mt-1 text-sm/6 text-gray-600">This form edits a list.</p>
        <% end %>

        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="col-span-full">
            <%= f.label :title, class: "block text-sm/6 font-medium text-gray-900" %>
            <div class="mt-2">
              <%= f.text_field :title, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", root_path, class: "text-sm/6 font-semibold text-gray-900" %>
      <%= f.submit class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60" %>
    </div>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <%= render "form", board: @board, list: @list %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">
    <%= render "form", board: @board, list: @list %>
  </div>
</div>